"""Add is_active column to users table

Revision ID: d161181583f7
Revises: f1d18d551c07
Create Date: 2025-05-07 16:22:26.409876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd161181583f7'
down_revision = 'f1d18d551c07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('users', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
